apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - postgres.yaml
  - backend.yaml
  - frontend.yaml
  - monitoring.yaml

configMapGenerator:
  - name: postgres-init-config
    files:
      - db_init.sql

images:
  - name: aneki-backend
    newName: aneki-registry.registry.twcstorage.ru/prod/aneki-backend
    newTag: 755a06d248c6723c114a390c405ae110b71b407e
  - name: aneki-frontend
    newName: aneki-registry.registry.twcstorage.ru/prod/aneki-frontend
    newTag: 755a06d248c6723c114a390c405ae110b71b407e
