apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - postgres.yaml
  - backend.yaml
  - frontend.yaml
  - monitoring.yaml

configMapGenerator:
  - name: postgres-init-config
    files:
      - db_init.sql

images:
  - name: aneki-backend
    newName: aneki-registry.registry.twcstorage.ru/prod/aneki-backend
    newTag: 3ddde1e566ff6c7c857a2888723c0113ccaf92c7
  - name: aneki-frontend
    newName: aneki-registry.registry.twcstorage.ru/prod/aneki-frontend
    newTag: 3ddde1e566ff6c7c857a2888723c0113ccaf92c7
