name: Release All

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  publish_frontend:
    uses: ElegantCone/aneki_frontend/.github/workflows/publish.yml@main
    with:
      image_tag: ${{ github.sha }}
      registry_host: aneki-registry.registry.twcstorage.ru
      image_name: prod/aneki-frontend
    secrets:
      REGISTRY_USERNAME: ${{ secrets.REGISTRY_USERNAME }}
      REGISTRY_PASSWORD: ${{ secrets.REGISTRY_TOKEN }}

  publish_backend:
    uses: ElegantCone/aneki/.github/workflows/publish.yml@main
    needs: publish_frontend
    with:
      image_tag: ${{ github.sha }}
      registry_host: aneki-registry.registry.twcstorage.ru
      image_name: prod/aneki-backend
    secrets:
      REGISTRY_USERNAME: ${{ secrets.REGISTRY_USERNAME }}
      REGISTRY_PASSWORD: ${{ secrets.REGISTRY_TOKEN }}

